package mknote

import "github.com/evanoberholster/exiftools/exif"

// Useful resources used in creating these tables:
//    http://www.exiv2.org/makernote.html
//    http://www.exiv2.org/tags-canon.html
//    http://www.exiv2.org/tags-nikon.html

// Known Maker Note fields
const (
	// common fields
	ISOSpeed                   exif.FieldName = "ISOSpeed"
	ColorMode                  exif.FieldName = "ColorMode"
	Quality                    exif.FieldName = "Quality"
	Sharpening                 exif.FieldName = "Sharpening"
	Focus                      exif.FieldName = "Focus"
	FlashSetting               exif.FieldName = "FlashSetting"
	FlashDevice                exif.FieldName = "FlashDevice"
	WhiteBalanceBias           exif.FieldName = "WhiteBalanceBias"
	WBRBLevels                 exif.FieldName = "WBRBLevels"
	ProgramShift               exif.FieldName = "ProgramShift"
	ExposureDiff               exif.FieldName = "ExposureDiff"
	ISOSelection               exif.FieldName = "ISOSelection"
	DataDump                   exif.FieldName = "DataDump"
	Preview                    exif.FieldName = "Preview"
	FlashComp                  exif.FieldName = "FlashComp"
	ISOSettings                exif.FieldName = "ISOSettings"
	ImageBoundary              exif.FieldName = "ImageBoundary"
	FlashExposureComp          exif.FieldName = "FlashExposureComp"
	FlashBracketComp           exif.FieldName = "FlashBracketComp"
	ExposureBracketComp        exif.FieldName = "ExposureBracketComp"
	ImageProcessing            exif.FieldName = "ImageProcessing"
	CropHiSpeed                exif.FieldName = "CropHiSpeed"
	ExposureTuning             exif.FieldName = "ExposureTuning"
	SerialNumber               exif.FieldName = "SerialNumber"
	ImageAuthentication        exif.FieldName = "ImageAuthentication"
	ActiveDLighting            exif.FieldName = "ActiveDLighting"
	VignetteControl            exif.FieldName = "VignetteControl"
	ImageAdjustment            exif.FieldName = "ImageAdjustment"
	ToneComp                   exif.FieldName = "ToneComp"
	AuxiliaryLens              exif.FieldName = "AuxiliaryLens"
	LensType                   exif.FieldName = "LensType"
	Lens                       exif.FieldName = "Lens"
	FocusDistance              exif.FieldName = "FocusDistance"
	DigitalZoom                exif.FieldName = "DigitalZoom"
	FlashMode                  exif.FieldName = "FlashMode"
	ShootingMode               exif.FieldName = "ShootingMode"
	AutoBracketRelease         exif.FieldName = "AutoBracketRelease"
	LensFStops                 exif.FieldName = "LensFStops"
	ContrastCurve              exif.FieldName = "ContrastCurve"
	ColorHue                   exif.FieldName = "ColorHue"
	SceneMode                  exif.FieldName = "SceneMode"
	HueAdjustment              exif.FieldName = "HueAdjustment"
	NEFCompression             exif.FieldName = "NEFCompression"
	NoiseReduction             exif.FieldName = "NoiseReduction"
	LinearizationTable         exif.FieldName = "LinearizationTable"
	RawImageCenter             exif.FieldName = "RawImageCenter"
	SensorPixelSize            exif.FieldName = "SensorPixelSize"
	SceneAssist                exif.FieldName = "SceneAssist"
	RetouchHistory             exif.FieldName = "RetouchHistory"
	ImageDataSize              exif.FieldName = "ImageDataSize"
	ImageCount                 exif.FieldName = "ImageCount"
	DeletedImageCount          exif.FieldName = "DeletedImageCount"
	ShutterCount               exif.FieldName = "ShutterCount"
	ImageOptimization          exif.FieldName = "ImageOptimization"
	SaturationText             exif.FieldName = "SaturationText"
	VariProgram                exif.FieldName = "VariProgram"
	ImageStabilization         exif.FieldName = "ImageStabilization"
	AFResponse                 exif.FieldName = "AFResponse"
	HighISONoiseReduction      exif.FieldName = "HighISONoiseReduction"
	ToningEffect               exif.FieldName = "ToningEffect"
	PrintIM                    exif.FieldName = "PrintIM"
	CaptureData                exif.FieldName = "CaptureData"
	CaptureVersion             exif.FieldName = "CaptureVersion"
	CaptureOffsets             exif.FieldName = "CaptureOffsets"
	ScanIFD                    exif.FieldName = "ScanIFD"
	ICCProfile                 exif.FieldName = "ICCProfile"
	CaptureOutput              exif.FieldName = "CaptureOutput"
	Panorama                   exif.FieldName = "Panorama"
	ImageType                  exif.FieldName = "ImageType"
	FirmwareVersion            exif.FieldName = "FirmwareVersion"
	FileNumber                 exif.FieldName = "FileNumber"
	OwnerName                  exif.FieldName = "OwnerName"
	CameraInfo                 exif.FieldName = "CameraInfo"
	CustomFunctions            exif.FieldName = "CustomFunctions"
	ModelID                    exif.FieldName = "ModelID"
	PictureInfo                exif.FieldName = "PictureInfo"
	ThumbnailImageValidArea    exif.FieldName = "ThumbnailImageValidArea"
	SerialNumberFormat         exif.FieldName = "SerialNumberFormat"
	SuperMacro                 exif.FieldName = "SuperMacro"
	OriginalDecisionDataOffset exif.FieldName = "OriginalDecisionDataOffset"
	WhiteBalanceTable          exif.FieldName = "WhiteBalanceTable"
	LensModel                  exif.FieldName = "LensModel"
	InternalSerialNumber       exif.FieldName = "InternalSerialNumber"
	DustRemovalData            exif.FieldName = "DustRemovalData"
	ProcessingInfo             exif.FieldName = "ProcessingInfo"
	MeasuredColor              exif.FieldName = "MeasuredColor"
	VRDOffset                  exif.FieldName = "VRDOffset"
	SensorInfo                 exif.FieldName = "SensorInfo"
	ColorData                  exif.FieldName = "ColorData"
)
